/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/container': RouteRecordInfo<'/container', '/container', Record<never, never>, Record<never, never>, '/container/commits/' | '/container/dashboard/' | '/container/database/' | '/container/fallback-sources/' | '/container/invitations/' | '/container/quota-overview/' | '/container/repositories/' | '/container/storage/' | '/container/users/'>,
    '/container/commits/': RouteRecordInfo<'/container/commits/', '/container/commits', Record<never, never>, Record<never, never>>,
    '/container/dashboard/': RouteRecordInfo<'/container/dashboard/', '/container/dashboard', Record<never, never>, Record<never, never>>,
    '/container/database/': RouteRecordInfo<'/container/database/', '/container/database', Record<never, never>, Record<never, never>>,
    '/container/fallback-sources/': RouteRecordInfo<'/container/fallback-sources/', '/container/fallback-sources', Record<never, never>, Record<never, never>>,
    '/container/invitations/': RouteRecordInfo<'/container/invitations/', '/container/invitations', Record<never, never>, Record<never, never>>,
    '/container/quota-overview/': RouteRecordInfo<'/container/quota-overview/', '/container/quota-overview', Record<never, never>, Record<never, never>>,
    '/container/repositories/': RouteRecordInfo<'/container/repositories/', '/container/repositories', Record<never, never>, Record<never, never>>,
    '/container/storage/': RouteRecordInfo<'/container/storage/', '/container/storage', Record<never, never>, Record<never, never>>,
    '/container/users/': RouteRecordInfo<'/container/users/', '/container/users', Record<never, never>, Record<never, never>>,
    '/quotas': RouteRecordInfo<'/quotas', '/quotas', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/container.vue': {
      routes: '/container' | '/container/commits/' | '/container/dashboard/' | '/container/database/' | '/container/fallback-sources/' | '/container/invitations/' | '/container/quota-overview/' | '/container/repositories/' | '/container/storage/' | '/container/users/' | '/container/commits' | '/container/dashboard' | '/container/database' | '/container/fallback-sources' | '/container/invitations' | '/container/quota-overview' | '/container/repositories' | '/container/storage' | '/container/users'
      views: 'default'
    }
    'src/pages/container/commits/index.vue': {
      routes: '/container/commits/'
      views: never
    }
    'src/pages/container/dashboard/index.vue': {
      routes: '/container/dashboard/'
      views: never
    }
    'src/pages/container/database/index.vue': {
      routes: '/container/database/'
      views: never
    }
    'src/pages/container/fallback-sources/index.vue': {
      routes: '/container/fallback-sources/'
      views: never
    }
    'src/pages/container/invitations/index.vue': {
      routes: '/container/invitations/'
      views: never
    }
    'src/pages/container/quota-overview/index.vue': {
      routes: '/container/quota-overview/'
      views: never
    }
    'src/pages/container/repositories/index.vue': {
      routes: '/container/repositories/'
      views: never
    }
    'src/pages/container/storage/index.vue': {
      routes: '/container/storage/'
      views: never
    }
    'src/pages/container/users/index.vue': {
      routes: '/container/users/'
      views: never
    }
    'src/pages/quotas.vue': {
      routes: '/quotas'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
